{
  "id": "GHSA-5qcg-w2cc-xffw",
  "summary": "Uncontrolled resource consumption in validators Python package",
  "details": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
  "aliases": [
    "CVE-2019-19588"
  ],
  "modified": "2023-02-16T23:08:37.409409Z",
  "published": "2020-01-21T20:32:09Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-835"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2020-01-21T20:31:40Z",
    "nvd_published_at": null
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-19588"
    },
    {
      "type": "WEB",
      "url": "https://github.com/kvesteri/validators/issues/86"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "validators",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/validators"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0.12.2"
            },
            {
              "fixed": "0.12.6"
            }
          ]
        }
      ],
      "versions": [
        "0.12.2",
        "0.12.3",
        "0.12.4",
        "0.12.5"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2020/01/GHSA-5qcg-w2cc-xffw/GHSA-5qcg-w2cc-xffw.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}