{
  "id": "GHSA-fffj-9qwg-qmh5",
  "summary": "Improper Input Validation in OpenCV",
  "details": "OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV 3.3.1.11).",
  "aliases": [
    "CVE-2016-1517"
  ],
  "modified": "2023-02-16T23:13:54.703218Z",
  "published": "2021-10-12T22:00:31Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2021-10-08T18:19:43Z",
    "nvd_published_at": null
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-1517"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/issues/5956"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/pull/9376"
    },
    {
      "type": "WEB",
      "url": "https://arxiv.org/pdf/1701.04739.pdf"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/opencv/opencv-python"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "opencv-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0",
        "3.1.0.0",
        "3.1.0.1",
        "3.1.0.2",
        "3.1.0.3",
        "3.1.0.4",
        "3.1.0.5",
        "3.2.0.6",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.10",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-fffj-9qwg-qmh5/GHSA-fffj-9qwg-qmh5.json"
      }
    },
    {
      "package": {
        "name": "opencv-contrib-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-contrib-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0.0",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.10",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-fffj-9qwg-qmh5/GHSA-fffj-9qwg-qmh5.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    }
  ]
}