{
  "id": "PYSEC-2022-241",
  "details": "The eziod package in PyPI before v0.0.1 included a code execution backdoor inserted by a third party.",
  "aliases": [
    "CVE-2022-34982"
  ],
  "modified": "2022-07-29T05:45:35.868408Z",
  "published": "2022-07-22T15:15:00Z",
  "references": [
    {
      "type": "PACKAGE",
      "url": "https://pypi.org/project/eziod/"
    },
    {
      "type": "WEB",
      "url": "http://pypi.doubanio.com/simple/request"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/alexw994/eziod/issues/1"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "eziod",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/eziod"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.0.2"
            }
          ]
        }
      ],
      "versions": [
        "0.0.1"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/eziod/PYSEC-2022-241.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}