{
  "id": "PYSEC-2019-64",
  "details": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
  "aliases": [
    "CVE-2019-19588"
  ],
  "modified": "2020-08-24T17:37:00Z",
  "published": "2019-12-05T01:15:00Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/kvesteri/validators/issues/86"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "validators",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/validators"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0.12.2"
            },
            {
              "fixed": "0.12.6"
            }
          ]
        }
      ],
      "versions": [
        "0.12.2",
        "0.12.3",
        "0.12.4",
        "0.12.5"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/validators/PYSEC-2019-64.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}