{
  "id": "PYSEC-2019-237",
  "details": "An issue was discovered in py-lmdb 0.97. For certain values of mp_flags, mdb_page_touch does not properly set up mc->mc_pg[mc->top], leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
  "aliases": [
    "CVE-2019-16225"
  ],
  "modified": "2021-12-14T08:17:08.271573Z",
  "published": "2019-09-11T15:15:00Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20write%20to%20illegal%20address"
    },
    {
      "type": "PACKAGE",
      "url": "https://pypi.org/project/lmdb"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16225"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "lmdb",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/lmdb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.98"
            }
          ]
        }
      ],
      "versions": [
        "0.58",
        "0.59",
        "0.60",
        "0.61",
        "0.62",
        "0.63",
        "0.64",
        "0.65",
        "0.66",
        "0.67",
        "0.68",
        "0.69",
        "0.70",
        "0.71",
        "0.73",
        "0.74",
        "0.75",
        "0.76",
        "0.77",
        "0.78",
        "0.79",
        "0.80",
        "0.81",
        "0.82",
        "0.83",
        "0.84",
        "0.85",
        "0.86",
        "0.87",
        "0.88",
        "0.89",
        "0.91",
        "0.92",
        "0.93",
        "0.94",
        "0.95",
        "0.96",
        "0.97"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/lmdb/PYSEC-2019-237.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}